// <auto-generated />
namespace Ecommerce.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CartIdToCartItem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CartIdToCartItem));
        
        string IMigrationMetadata.Id
        {
            get { return "202108111814452_CartIdToCartItem"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
